export const data = [
  {
    id: 1,
    issue_name: "Overspeed issue",
    issue_number: 226700,
    comment:
      "That's not good. The Cargo manifest is crucial thing for us. Are you sure you have checked the usual places and Cargo manifest is crucial thing for us.",
    caused_by: "Equipement Failure",
    cargo_name: "Athenian Phoenix",
    task: "2/4",
    resolver: "VCG",
    assigned: "SG",
    assigned_name: "Sarah Gilmore",
    raised_by: "Bary Irons",
    due: "5 hrs",
    created_on: "25 Nov 23",
    updated_on: "Thus 11:58",
    status: "Open",
  },
  {
    id: 2,
    issue_name: "Overspeed issue",
    issue_number: 226701,
    comment:
      "That's not good. The Cargo manifest is crucial thing for us. Are you sure you have checked the usual places and Cargo manifest is crucial thing for us.",
    caused_by: "Equipement Failure",
    cargo_name: "Athenian Phoenix",
    task: "2/4",
    resolver: "VCG",
    assigned: "SG",
    assigned_name: "Sarah Gilmore",
    raised_by: "Bary Irons",
    due: "overdue",
    created_on: "25 Nov 23",
    updated_on: "Thus 11:58",
    status: "Open",
  },
  {
    id: 3,
    issue_name: "Overspeed issue",
    issue_number: 226702,
    comment:
      "That's not good. The Cargo manifest is crucial thing for us. Are you sure you have checked the usual places and Cargo manifest is crucial thing for us.",
    caused_by: "Equipement Failure",
    cargo_name: "Athenian Phoenix",
    task: "2/4",
    resolver: "VCG",
    assigned: "AJ",
    assigned_name: "Sarah Gilmore",
    raised_by: "Bary Irons",
    due: "5 hrs",
    created_on: "25 Nov 23",
    updated_on: "Thus 11:58",
    status: "Open",
  },
  {
    id: 4,
    issue_name: "Overspeed issue",
    issue_number: 226704,
    comment:
      "That's not good. The Cargo manifest is crucial thing for us. Are you sure you have checked the usual places and Cargo manifest is crucial thing for us.",
    caused_by: "Equipement Failure",
    cargo_name: "Athenian Phoenix",
    task: "2/4",
    resolver: "VCG",
    assigned: "SG",
    assigned_name: "Sarah Gilmore",
    raised_by: "Bary Irons",
    due: "overdue",
    created_on: "25 Nov 23",
    updated_on: "Thus 11:58",
    status: "Open",
  },
  {
    id: 5,
    issue_name: "Overspeed issue",
    issue_number: 226705,
    comment:
      "That's not good. The Cargo manifest is crucial thing for us. Are you sure you have checked the usual places and Cargo manifest is crucial thing for us.",
    caused_by: "Equipement Failure",
    cargo_name: "Athenian Phoenix",
    task: "2/4",
    resolver: "VCG",
    assigned_name: "Sarah Gilmore",
    raised_by: "Bary Irons",
    due: "overdue",
    created_on: "25 Nov 23",
    updated_on: "Thus 11:58",
    status: "Open",
  },
  {
    id: 6,
    issue_name: "Overspeed issue",
    issue_number: 226706,
    comment:
      "That's not good. The Cargo manifest is crucial thing for us. Are you sure you have checked the usual places and Cargo manifest is crucial thing for us.",
    caused_by: "Equipement Failure",
    cargo_name: "Athenian Phoenix",
    task: "2/4",
    resolver: "VCG",
    assigned: "SG",
    assigned_name: "Sarah Gilmore",
    raised_by: "Bary Irons",
    due: "5 hrs",
    created_on: "25 Nov 23",
    updated_on: "Thus 11:58",
    status: "Open",
  },
  {
    id: 7,
    issue_name: "Overspeed issue",
    issue_number: 226707,
    comment:
      "That's not good. The Cargo manifest is crucial thing for us. Are you sure you have checked the usual places and Cargo manifest is crucial thing for us.",
    caused_by: "Equipement Failure",
    cargo_name: "Athenian Phoenix",
    task: "2/4",
    resolver: "VCG",
    assigned: "SG",
    assigned_name: "Sarah Gilmore",
    raised_by: "Bary Irons",
    due: "5 hrs",
    created_on: "25 Nov 23",
    updated_on: "Thus 11:58",
    status: "Open",
  },
  {
    id: 8,
    issue_name: "Overspeed issue",
    issue_number: 226708,
    comment:
      "That's not good. The Cargo manifest is crucial thing for us. Are you sure you have checked the usual places and Cargo manifest is crucial thing for us.",
    caused_by: "Equipement Failure",
    cargo_name: "Athenian Phoenix",
    task: "2/4",
    resolver: "VCG",
    assigned: "SG",
    assigned_name: "Sarah Gilmore",
    raised_by: "Bary Irons",
    due: "overdue",
    created_on: "25 Nov 23",
    updated_on: "Thus 11:58",
    status: "Open",
  },
  {
    id: 9,
    issue_name: "Overspeed issue",
    issue_number: 226709,
    comment:
      "That's not good. The Cargo manifest is crucial thing for us. Are you sure you have checked the usual places and Cargo manifest is crucial thing for us.",
    caused_by: "Equipement Failure",
    cargo_name: "Athenian Phoenix",
    task: "2/4",
    resolver: "VCG",
    assigned: "SG",
    assigned_name: "Sarah Gilmore",
    raised_by: "Bary Irons",
    due: "overdue",
    created_on: "25 Nov 23",
    updated_on: "Thus 11:58",
    status: "Open",
  },
  {
    id: 10,
    issue_name: "Overspeed issue",
    issue_number: 226710,
    comment:
      "That's not good. The Cargo manifest is crucial thing for us. Are you sure you have checked the usual places and Cargo manifest is crucial thing for us.",
    caused_by: "Equipement Failure",
    cargo_name: "Athenian Phoenix",
    task: "2/4",
    resolver: "VCG",
    assigned_name: "Sarah Gilmore",
    raised_by: "Bary Irons",
    due: "overdue",
    created_on: "25 Nov 23",
    updated_on: "Thus 11:58",
    status: "Open",
  },
  {
    id: 11,
    issue_name: "Overspeed issue",
    issue_number: 226711,
    comment:
      "That's not good. The Cargo manifest is crucial thing for us. Are you sure you have checked the usual places and Cargo manifest is crucial thing for us.",
    caused_by: "Equipement Failure",
    cargo_name: "Athenian Phoenix",
    task: "2/4",
    resolver: "VCG",
    assigned: "AJ",
    assigned_name: "Sarah Gilmore",
    raised_by: "Bary Irons",
    due: "5 hrs",
    created_on: "25 Nov 23",
    updated_on: "Thus 11:58",
    status: "Open",
  },
  {
    id: 12,
    issue_name: "Overspeed issue",
    issue_number: 226712,
    comment:
      "That's not good. The Cargo manifest is crucial thing for us. Are you sure you have checked the usual places and Cargo manifest is crucial thing for us.",
    caused_by: "Equipement Failure",
    cargo_name: "Athenian Phoenix",
    task: "2/4",
    resolver: "VCG",
    assigned_name: "Sarah Gilmore",
    raised_by: "Bary Irons",
    due: "overdue",
    created_on: "25 Nov 23",
    updated_on: "Thus 11:58",
    status: "Open",
  },
  {
    id: 13,
    issue_name: "Overspeed issue",
    issue_number: 226713,
    comment:
      "That's not good. The Cargo manifest is crucial thing for us. Are you sure you have checked the usual places and Cargo manifest is crucial thing for us.",
    caused_by: "Equipement Failure",
    cargo_name: "Athenian Phoenix",
    task: "2/4",
    resolver: "VCG",
    assigned: "SG",
    assigned_name: "Sarah Gilmore",
    raised_by: "Bary Irons",
    due: "overdue",
    created_on: "25 Nov 23",
    updated_on: "Thus 11:58",
    status: "Open",
  },
  {
    id: 14,
    issue_name: "Overspeed issue",
    issue_number: 226714,
    comment:
      "That's not good. The Cargo manifest is crucial thing for us. Are you sure you have checked the usual places and Cargo manifest is crucial thing for us.",
    caused_by: "Equipement Failure",
    cargo_name: "Athenian Phoenix",
    task: "2/4",
    resolver: "VCG",
    assigned: "AJ",
    assigned_name: "Sarah Gilmore",
    raised_by: "Bary Irons",
    due: "overdue",
    created_on: "25 Nov 23",
    updated_on: "Thus 11:58",
    status: "Open",
  },
  {
    id: 15,
    issue_name: "Overspeed issue",
    issue_number: 226715,
    comment:
      "That's not good. The Cargo manifest is crucial thing for us. Are you sure you have checked the usual places and Cargo manifest is crucial thing for us.",
    caused_by: "Equipement Failure",
    cargo_name: "Athenian Phoenix",
    task: "2/4",
    resolver: "VCG",
    assigned_name: "Sarah Gilmore",
    raised_by: "Bary Irons",
    due: "overdue",
    created_on: "25 Nov 23",
    updated_on: "Thus 11:58",
    status: "Open",
  },
  {
    id: 16,
    issue_name: "Overspeed issue",
    issue_number: 226716,
    comment:
      "That's not good. The Cargo manifest is crucial thing for us. Are you sure you have checked the usual places and Cargo manifest is crucial thing for us.",
    caused_by: "Equipement Failure",
    cargo_name: "Athenian Phoenix",
    task: "2/4",
    resolver: "VCG",
    assigned: "SG",
    assigned_name: "Sarah Gilmore",
    raised_by: "Bary Irons",
    due: "overdue",
    created_on: "25 Nov 23",
    updated_on: "Thus 11:58",
    status: "Open",
  },
  {
    id: 17,
    issue_name: "Overspeed issue",
    issue_number: 226717,
    comment:
      "That's not good. The Cargo manifest is crucial thing for us. Are you sure you have checked the usual places and Cargo manifest is crucial thing for us.",
    caused_by: "Equipement Failure",
    cargo_name: "Athenian Phoenix",
    task: "2/4",
    resolver: "VCG",
    assigned: "SG",
    assigned_name: "Sarah Gilmore",
    raised_by: "Bary Irons",
    due: "5 hrs",
    created_on: "25 Nov 23",
    updated_on: "Thus 11:58",
    status: "Open",
  },
  {
    id: 18,
    issue_name: "Overspeed issue",
    issue_number: 226718,
    comment:
      "That's not good. The Cargo manifest is crucial thing for us. Are you sure you have checked the usual places and Cargo manifest is crucial thing for us.",
    caused_by: "Equipement Failure",
    cargo_name: "Athenian Phoenix",
    task: "2/4",
    resolver: "VCG",
    assigned_name: "Sarah Gilmore",
    raised_by: "Bary Irons",
    due: "overdue",
    created_on: "25 Nov 23",
    updated_on: "Thus 11:58",
    status: "Open",
  },
  {
    id: 19,
    issue_name: "Overspeed issue",
    issue_number: 226719,
    comment:
      "That's not good. The Cargo manifest is crucial thing for us. Are you sure you have checked the usual places and Cargo manifest is crucial thing for us.",
    caused_by: "Equipement Failure",
    cargo_name: "Athenian Phoenix",
    task: "2/4",
    resolver: "VCG",
    assigned: "SG",
    assigned_name: "Sarah Gilmore",
    raised_by: "Bary Irons",
    due: "5 hrs",
    created_on: "25 Nov 23",
    updated_on: "Thus 11:58",
    status: "Close",
  },
  {
    id: 20,
    issue_name: "Overspeed issue",
    issue_number: 226720,
    comment:
      "That's not good. The Cargo manifest is crucial thing for us. Are you sure you have checked the usual places and Cargo manifest is crucial thing for us.",
    caused_by: "Equipement Failure",
    cargo_name: "Athenian Phoenix",
    task: "2/4",
    resolver: "VCG",
    assigned: "SG",
    assigned_name: "Sarah Gilmore",
    raised_by: "Bary Irons",
    due: "overdue",
    created_on: "25 Nov 23",
    updated_on: "Thus 11:58",
    status: "Open",
  },
  {
    id: 21,
    issue_name: "Overspeed issue",
    issue_number: 226721,
    comment:
      "That's not good. The Cargo manifest is crucial thing for us. Are you sure you have checked the usual places and Cargo manifest is crucial thing for us.",
    caused_by: "Equipement Failure",
    cargo_name: "Athenian Phoenix",
    task: "2/4",
    resolver: "VCG",
    assigned: "SG",
    assigned_name: "Sarah Gilmore",
    raised_by: "Bary Irons",
    due: "5 hrs",
    created_on: "25 Nov 23",
    updated_on: "Thus 11:58",
    status: "Open",
  },
  {
    id: 22,
    issue_name: "Overspeed issue",
    issue_number: 226722,
    comment:
      "That's not good. The Cargo manifest is crucial thing for us. Are you sure you have checked the usual places and Cargo manifest is crucial thing for us.",
    caused_by: "Equipement Failure",
    cargo_name: "Athenian Phoenix",
    task: "2/4",
    resolver: "VCG",
    assigned_name: "Sarah Gilmore",
    raised_by: "Bary Irons",
    due: "overdue",
    created_on: "25 Nov 23",
    updated_on: "Thus 11:58",
    status: "Close",
  },
];
